services:
  cypress:
    image: cypress/included:12.17.0 # Adjust the version number to match the version of Cypress you are using
    environment:
      - CYPRESS_BASE_URL=http://frontend:3000/  # Adjust to match the URL of your frontend service
      - CYPRESS_BACKEND=http://api.localhost/  # Adjust to match the URL of your backend service
    depends_on:
      - frontend
      - control
      - mongo
    volumes:
      - ./e2e:/e2e  # Mount your project directory to /e2e in the Cypress container
    working_dir: /e2e  # Set the working directory to /e2e in the Cypress container
    command: cypress run  # Run Cypress tests
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongotestdata:/data/db
      - ./tools/01-mongo-init.js:/docker-entrypoint-initdb.d/01-mongo-init.js:ro
      - ./tools/02-mongo-fixtures.js:/docker-entrypoint-initdb.d/02-mongo-fixtures.js:ro

volumes:
  mongotestdata:

