version: '3.3'
services:
  backend:
    image: localhost:5001/PLACEHOLDER_NAME-backend:local
    environment:
      LOG_LEVEL: TRACE
      WEBAPP_URL: http://app.PLACEHOLDER_NAME.localhost
      MONGO_CONNECTION_STRING: mongodb://control-msc-user:control-msc-pass@mongo:27017/PLACEHOLDER_NAME_DB
      ALLOW_DEMO_LOGIN: "true"
      DEMO_LOGIN_COOKIE_DOMAIN: app.PLACEHOLDER_NAME.localhost
      JWT_SECRET_TOKEN: "secret"
  storage:
    image: localhost:5001/PLACEHOLDER_NAME-storage:local
    environment:
      LOG_LEVEL: TRACE
      WEBAPP_URL: http://app.PLACEHOLDER_NAME.localhost
      JWT_SECRET_TOKEN: "secret"
  frontend:
    image: localhost:5001/PLACEHOLDER_NAME-frontend:local
    networks:
      default:
        aliases:
          - app.PLACEHOLDER_NAME.localhost
          - api.PLACEHOLDER_NAME.localhost
    build:
      args:
        # Real envs
        - REACT_APP_API_ENDPOINT=http://api.PLACEHOLDER_NAME.localhost
        - REACT_APP_STORAGE_API_ENDPOINT=http://api.PLACEHOLDER_NAME.localhost/storage
        - REACT_APP_LOG_LEVEL=DEBUG
    environment:
      - SSL=false
      - WEBAPP_DOMAIN=app.PLACEHOLDER_NAME.localhost
      - API_DOMAIN=api.PLACEHOLDER_NAME.localhost
      - BACKEND_SERVER_API=backend:3001
    extra_hosts:
      - "app.PLACEHOLDER_NAME.localhost:127.0.0.1"
      - "api.PLACEHOLDER_NAME.localhost:127.0.0.1"
    ports:
      - "80:80"
      - "443:443"
  cypress:
    image: cypress/included:12.17.0 # Adjust the version number to match the version of Cypress you are using
    environment:
      - CYPRESS_BASE_URL=http://app.PLACEHOLDER_NAME.localhost/  # Adjust to match the URL of your frontend service
      - CYPRESS_BACKEND=http://api.PLACEHOLDER_NAME.localhost/  # Adjust to match the URL of your backend service
    depends_on:
      - frontend
      - backend
      - mongo
    volumes:
      - ./e2e:/e2e  # Mount your project directory to /e2e in the Cypress container
    working_dir: /e2e  # Set the working directory to /e2e in the Cypress container
    command: cypress run  # Run Cypress tests
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongotestdata:/data/db
      - ./tools/01-mongo-init.js:/docker-entrypoint-initdb.d/01-mongo-init.js:ro
      - ./tools/02-mongo-fixtures.js:/docker-entrypoint-initdb.d/02-mongo-fixtures.js:ro

volumes:
  mongotestdata:

