# nginx/Dockerfile
FROM nginx:latest

## Copy your template into the container.
#COPY nginx.conf.template /etc/nginx/nginx.conf.template

# Finally, run NGINX in the foreground.
CMD ["nginx", "-g", "daemon off;"]
