name: Light house tests
on:
  pull_request:
    branches: [ "main" ]
    paths: [
        "microservices/control/**",
        "microservices/storage/**",
        "frontend/**",
        ".github/**",
        "nginx/**",
        "seo/**",
    ]
  workflow_call:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run the application
        working-directory: .
        run: yarn start:docker

      - name: Run Lighthouse tests
        working-directory: .
        run: yarn lighthouse:run